### ISSUE TITLE
System Requiring Multiple Components

### ISSUE THREAD

**Issue by bojjenclon** [RoganMurley/hitagi.js#10]
Perhaps I missed it or simply misunderstood something, but is there any way to make a system look for/require multiple components? With the key-value sort of approach I see in the System page of the wiki, it appears you can only create functionality for one required component at a time, and must just assume the rest are there if multiple are needed. In most other ECS solutions I've used, there is usually a way to require multiple components from the get-go (e.g. [tiny-ecs](https://github.com/bvalosek/tiny-ecs)).

**Comment by RoganMurley** [comment]
Unfortunately there's no really nice way of doing it yet, but you can use the "has" method entities expose like so:

```
var MySystem = {
    update: {
        componentA: function (entity) {
            if (entity.has("componentB")) {
                // Do stuff here
            }
        }
    }
};
```

**Comment by bojjenclon** [comment]
I noticed you said "yet," does that mean you intend on adding this functionality eventually?

**Comment by RoganMurley** [comment]
If I can think of (or someone proposes) a sufficiently nice way of doing this I'd be happy to add it in.
